services:
    security.authentication.listener.form_login_captcha:
        class: LoginRecaptcha\Bundle\Security\Firewall\CaptchaFormAuthenticationListener
        parent: security.authentication.listener.form
        calls:
            - [setCacheClient, ['@?login_recaptcha.cache_client']]

    login_recaptcha.failed_authentication.listener:
        class: LoginRecaptcha\Bundle\EventListener\FailedAuthenticationListener
        arguments:
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
        calls:
            - [setCaptchaFormAuthenticationListener, ['@?login_recaptcha.cache_client']]

